version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nutrimurt-postgres
    environment:
      POSTGRES_USER: nutrimurt
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nutrimurtdb
    expose:
      - "5432"
    volumes:
      - nutrimurt_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./nutrimurt.Api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=nutrimurtdb;Username=nutrimurt;Password=${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
    expose:
      - "8080"

  pyservice:
    build:
      context: ./nutrimurt.PyService
    environment:
      CONNECTION_STRING: postgresql+psycopg://nutrimurt:${DB_PASSWORD}@postgres:5432/nutrimurtdb
      ENV: development
      WEBSITE_URL: https://localhost
      MAILGUN_FROM: "NutriMurt <noreply@nutrimurt.com.br>"
      # MAILGUN_API_KEY: ...
      # MAILGUN_DOMAIN: ...
    depends_on:
      - postgres
    expose:
      - "8000"

  gateway:
    image: nginx:alpine
    depends_on:
      - api
      - pyservice
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.dev-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./nutrimurt.Web/dist:/usr/share/nginx/html:ro
      - ./infra/certs:/etc/nginx/certs:ro
volumes:
  nutrimurt_pgdata:
