CREATE TABLE "patient_diaries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_diaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patient_diary_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_diary_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"patient_diary_id" integer,
	"date" date NOT NULL,
	"meal_type" integer NOT NULL,
	"time" timestamp with time zone,
	"food" text NOT NULL,
	"amount" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patient_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"patient_id" integer NOT NULL,
	"url_id" char(32) NOT NULL,
	"type" integer NOT NULL,
	"questionnary_id" integer,
	"diary_id" integer,
	"last_answered" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "patient_meal_plan_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_meal_plan_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"patient_meal_plan_id" integer NOT NULL,
	"meal_type" integer NOT NULL,
	"food" varchar(100) NOT NULL,
	"amount" varchar(50) NOT NULL,
	"substitution" boolean NOT NULL,
	"substitution2" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patient_meal_plans" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_meal_plans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"patient_id" integer NOT NULL,
	"name" varchar(200) NOT NULL,
	"total_cals" integer NOT NULL,
	"meal_plan_date" date NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patient_question_answer_alternatives" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_question_answer_alternatives_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question_id" integer NOT NULL,
	"alternative" text NOT NULL,
	"patient_link_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patient_question_answers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_question_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question_id" integer NOT NULL,
	"answer" text NOT NULL,
	"patient_link_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patients" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" varchar(200) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" text NOT NULL,
	"cpf" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"birth" date,
	"weight" integer NOT NULL,
	"height" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "question_alternatives" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "question_alternatives_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"alternative" varchar(500) NOT NULL,
	"question_id" integer
);
--> statement-breakpoint
CREATE TABLE "questionnaries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "questionnaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "questions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question_text" varchar(500) NOT NULL,
	"question_type" integer NOT NULL,
	"questionnary_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_email_send_counters" (
	"user_id" text PRIMARY KEY NOT NULL,
	"window_date" date NOT NULL,
	"send_count" integer NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "patient_diary_entries" ADD CONSTRAINT "patient_diary_entries_patient_diary_id_patient_diaries_id_fk" FOREIGN KEY ("patient_diary_id") REFERENCES "public"."patient_diaries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient_links" ADD CONSTRAINT "patient_links_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient_links" ADD CONSTRAINT "patient_links_questionnary_id_questionnaries_id_fk" FOREIGN KEY ("questionnary_id") REFERENCES "public"."questionnaries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient_links" ADD CONSTRAINT "patient_links_diary_id_patient_diaries_id_fk" FOREIGN KEY ("diary_id") REFERENCES "public"."patient_diaries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient_meal_plan_entries" ADD CONSTRAINT "patient_meal_plan_entries_patient_meal_plan_id_patient_meal_plans_id_fk" FOREIGN KEY ("patient_meal_plan_id") REFERENCES "public"."patient_meal_plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient_question_answer_alternatives" ADD CONSTRAINT "patient_question_answer_alternatives_patient_link_id_patient_links_id_fk" FOREIGN KEY ("patient_link_id") REFERENCES "public"."patient_links"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient_question_answers" ADD CONSTRAINT "patient_question_answers_patient_link_id_patient_links_id_fk" FOREIGN KEY ("patient_link_id") REFERENCES "public"."patient_links"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "question_alternatives" ADD CONSTRAINT "question_alternatives_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_questionnary_id_questionnaries_id_fk" FOREIGN KEY ("questionnary_id") REFERENCES "public"."questionnaries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_patient_diary_entries_patient_diary_id" ON "patient_diary_entries" USING btree ("patient_diary_id");--> statement-breakpoint
CREATE INDEX "ix_patient_links_diary_id" ON "patient_links" USING btree ("diary_id");--> statement-breakpoint
CREATE INDEX "ix_patient_links_patient_id" ON "patient_links" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "ix_patient_links_questionnary_id" ON "patient_links" USING btree ("questionnary_id");--> statement-breakpoint
CREATE INDEX "ix_patient_links_user_id" ON "patient_links" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ix_patient_meal_plan_entries_patient_meal_plan_id" ON "patient_meal_plan_entries" USING btree ("patient_meal_plan_id");--> statement-breakpoint
CREATE INDEX "ix_patient_meal_plans_user_id" ON "patient_meal_plans" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ix_patient_question_answer_alternatives_patient_link_id" ON "patient_question_answer_alternatives" USING btree ("patient_link_id");--> statement-breakpoint
CREATE INDEX "ix_patient_question_answers_patient_link_id" ON "patient_question_answers" USING btree ("patient_link_id");--> statement-breakpoint
CREATE INDEX "ix_patients_user_id" ON "patients" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ix_question_alternatives_question_id" ON "question_alternatives" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "ix_questionnaries_user_id" ON "questionnaries" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ix_questions_questionnary_id" ON "questions" USING btree ("questionnary_id");