import { useEffect, useState, type FormEvent } from 'react';
import { toast } from 'react-toastify';
import { answersApi } from './pyApi';
import type { PatientLink, DiaryEntry } from './types';

interface Props {
  patientLink: PatientLink | null;
}

export default function DiaryAnswer({ patientLink }: Props) {
  const [formPatientLink, setFormPatientLink] = useState<PatientLink | null>(patientLink);
  const [status, setStatus] = useState<'idle' | 'submitting' | 'success' | 'error'>('idle');
  const [entries, setEntries] = useState<DiaryEntry[]>([]);
  const [date, setDate] = useState<string>('');
  const [time, setTime] = useState<string>('');
  const [food, setFood] = useState<string>('');
  const [amount, setAmount] = useState<string>('');

  const handleSubmit = () => {
    const newEntry: DiaryEntry = {
      id: 0, // ID would be generated by backend in real scenario
      date,
      time,
      food,
      amount
    };
    setEntries([...entries, newEntry]);
    setDate('');
    setTime('');
    setFood('');
    setAmount('');
  };

  useEffect(() => {
    setFormPatientLink(patientLink);
  }, [patientLink]);

  const onSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!formPatientLink) return;
    try {
      setStatus('submitting');
      await answersApi.save(formPatientLink);
      setStatus('success');
      toast.success('Diário enviado com sucesso');
    } catch (err) {
      setStatus('error');
      console.error('Error saving answers', err);
      toast.error('Falha ao enviar diário. Tente novamente.');
    }
  };

  return (
    <main className="relative isolate min-h-screen overflow-hidden bg-slate-950 text-white">
      <form onSubmit={onSubmit} className="space-y-6">
        <div className="absolute left-1/2 top-10 -z-10 h-96 w-96 -translate-x-1/2 rounded-full bg-teal-800/20 blur-3xl" />
        <div className="mx-auto flex min-h-screen max-w-6xl flex-col px-6 pb-16 pt-10 lg:px-10">
          <section className="space-y-6 relative rounded-3xl border border-white/10 bg-gradient-to-b from-white/10 via-slate-900/60 to-slate-950 p-6 shadow-2xl">
            <p className="text-slate-400">Componente de diário em construção.</p>
          </section>

          <div>
            Data:<input type="text" value={date} className="bg-transparent border-b border-slate-700 w-full" />
            Hora:<input type="text" value={time} className="bg-transparent border-b border-slate-700 w-full" />
            Alimento:<input type="text" value={food} className="bg-transparent border-b border-slate-700 w-full" />
            Quantidade:<input type="text" value={amount} className="bg-transparent border-b border-slate-700 w-full" />
            <button type="button" className="rounded bg-emerald-500 px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-400"
                                onClick={handleSubmit}
                                // disabled={!selectedQuestionaryId || submitting}
                            >
                                +
                            </button>


          </div>
          {entries.map((entry) => (
            <section key={entry.id} className="space-y-2">
              <input type="text" value={entry.date} disabled className="bg-transparent border-b border-slate-700 w-full" />
              <input type="text" value={entry.time} disabled className="bg-transparent border-b border-slate-700 w-full" />
              <input type="text" value={entry.food} disabled className="bg-transparent border-b border-slate-700 w-full" />
            </section>
          ))}


          <button
            type="submit"
            disabled={status === 'submitting'}
            className="rounded bg-emerald-500 px-4 py-2 text-white hover:bg-emerald-600"
          >
            {status === 'submitting' ? 'Enviando...' : 'Enviar respostas'}
          </button>
        </div>
      </form>
    </main>
  );
}
