// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nutrimurt.Api.Data;

#nullable disable

namespace nutrimurt.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225160340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("nutrimurt.Api.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birth")
                        .HasColumnType("date")
                        .HasColumnName("birth");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientDiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_patient_diaries");

                    b.ToTable("patient_diaries", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientDiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("food");

                    b.Property<int?>("PatientDiaryId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_diary_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_patient_diary_entries");

                    b.HasIndex("PatientDiaryId")
                        .HasDatabaseName("ix_patient_diary_entries_patient_diary_id");

                    b.ToTable("patient_diary_entries", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiaryId")
                        .HasColumnType("integer")
                        .HasColumnName("diary_id");

                    b.Property<DateTime?>("LastAnswered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_answered");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int?>("QuestionnaryId")
                        .HasColumnType("integer")
                        .HasColumnName("questionnary_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("UrlId")
                        .IsRequired()
                        .HasColumnType("CHAR(32)")
                        .HasColumnName("url_id");

                    b.HasKey("Id")
                        .HasName("pk_patient_links");

                    b.HasIndex("DiaryId")
                        .HasDatabaseName("ix_patient_links_diary_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_links_patient_id");

                    b.HasIndex("QuestionnaryId")
                        .HasDatabaseName("ix_patient_links_questionnary_id");

                    b.ToTable("patient_links", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("PatientLinkId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_link_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_patient_question_answers");

                    b.HasIndex("PatientLinkId")
                        .HasDatabaseName("ix_patient_question_answers_patient_link_id");

                    b.ToTable("patient_question_answers", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientQuestionAnswerAlternative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alternative")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternative");

                    b.Property<int>("PatientLinkId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_link_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_patient_question_answer_alternatives");

                    b.HasIndex("PatientLinkId")
                        .HasDatabaseName("ix_patient_question_answer_alternatives_patient_link_id");

                    b.ToTable("patient_question_answer_alternatives", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.Property<int>("QuestionnaryId")
                        .HasColumnType("integer")
                        .HasColumnName("questionnary_id");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("QuestionnaryId")
                        .HasDatabaseName("ix_questions_questionnary_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.QuestionAlternatives", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alternative")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternative");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_question_alternatives");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_alternatives_question_id");

                    b.ToTable("question_alternatives", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.Questionnaries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_questionnaries");

                    b.ToTable("questionnaries", (string)null);
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientDiaryEntry", b =>
                {
                    b.HasOne("nutrimurt.Api.Models.PatientDiary", null)
                        .WithMany("Entries")
                        .HasForeignKey("PatientDiaryId")
                        .HasConstraintName("fk_patient_diary_entries_patient_diaries_patient_diary_id");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientLink", b =>
                {
                    b.HasOne("nutrimurt.Api.Models.PatientDiary", "Diary")
                        .WithMany()
                        .HasForeignKey("DiaryId")
                        .HasConstraintName("fk_patient_links_patient_diaries_diary_id");

                    b.HasOne("nutrimurt.Api.Models.Patient", "Patient")
                        .WithMany("PatientLinks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_links_patients_patient_id");

                    b.HasOne("nutrimurt.Api.Models.Questionnaries", "Questionnary")
                        .WithMany()
                        .HasForeignKey("QuestionnaryId")
                        .HasConstraintName("fk_patient_links_questionnaries_questionnary_id");

                    b.Navigation("Diary");

                    b.Navigation("Patient");

                    b.Navigation("Questionnary");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientQuestionAnswer", b =>
                {
                    b.HasOne("nutrimurt.Api.Models.PatientLink", "PatientLink")
                        .WithMany()
                        .HasForeignKey("PatientLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_question_answers_patient_links_patient_link_id");

                    b.Navigation("PatientLink");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientQuestionAnswerAlternative", b =>
                {
                    b.HasOne("nutrimurt.Api.Models.PatientLink", "PatientLink")
                        .WithMany()
                        .HasForeignKey("PatientLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_question_answer_alternatives_patient_links_patient_");

                    b.Navigation("PatientLink");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.Question", b =>
                {
                    b.HasOne("nutrimurt.Api.Models.Questionnaries", "Questionnary")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_questionnaries_questionnary_id");

                    b.Navigation("Questionnary");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.QuestionAlternatives", b =>
                {
                    b.HasOne("nutrimurt.Api.Models.Question", null)
                        .WithMany("Alternatives")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_question_alternatives_questions_question_id");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.Patient", b =>
                {
                    b.Navigation("PatientLinks");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.PatientDiary", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.Question", b =>
                {
                    b.Navigation("Alternatives");
                });

            modelBuilder.Entity("nutrimurt.Api.Models.Questionnaries", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
