class Guardrails:
    MAX_EMAIL_SENDS_PER_DAY = 10
    MAX_DIARY_ENTRIES_PER_DAY = 50
    MAX_DIARY_DISTINCT_DAYS = 90
    MAX_TOTAL_DIARY_ENTRIES = 4500       # 90 * 50
    MAX_TEXT_LENGTH = 500
    MAX_ANSWER_ALTERNATIVES_PER_QUESTION = 10
    MAX_QUESTIONS_PER_SUBMISSION = 10
